#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 9

enum {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_EQ = 3,
  anon_sym_SEMI = 4,
  anon_sym_print = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_if = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_else = 11,
  sym_number = 12,
  sym_string = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  sym_nil = 16,
  anon_sym_BANG = 17,
  anon_sym_DASH = 18,
  anon_sym_COMMA = 19,
  anon_sym_EQ_EQ = 20,
  anon_sym_BANG_EQ = 21,
  anon_sym_LT = 22,
  anon_sym_LT_EQ = 23,
  anon_sym_GT = 24,
  anon_sym_GT_EQ = 25,
  anon_sym_PLUS = 26,
  anon_sym_STAR = 27,
  anon_sym_SLASH = 28,
  anon_sym_QMARK = 29,
  anon_sym_COLON = 30,
  anon_sym_SLASH_SLASH = 31,
  aux_sym_comment_token1 = 32,
  anon_sym_SLASH_STAR = 33,
  aux_sym_comment_token2 = 34,
  anon_sym_STAR_SLASH = 35,
  sym_program = 36,
  sym__declaration = 37,
  sym_variable_declaration = 38,
  sym__statement = 39,
  sym_expression_statement = 40,
  sym_print_statement = 41,
  sym_block_statement = 42,
  sym_if_statement = 43,
  sym__expression = 44,
  sym__literal = 45,
  sym_boolean = 46,
  sym_group_expression = 47,
  sym_unary_expression = 48,
  sym_binary_expression = 49,
  sym_ternary_expression = 50,
  sym_assignment_expression = 51,
  sym_comment = 52,
  aux_sym_program_repeat1 = 53,
  aux_sym_comment_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_print] = "print",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_else] = "else",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym__statement] = "_statement",
  [sym_expression_statement] = "expression_statement",
  [sym_print_statement] = "print_statement",
  [sym_block_statement] = "block_statement",
  [sym_if_statement] = "if_statement",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym_group_expression] = "group_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_ternary_expression] = "ternary_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_else] = anon_sym_else,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym__statement] = sym__statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_block_statement] = sym_block_statement,
  [sym_if_statement] = sym_if_statement,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym_group_expression] = sym_group_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_ternary_expression] = sym_ternary_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_group_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_condition = 1,
  field_else = 2,
  field_expression = 3,
  field_initialiser = 4,
  field_left = 5,
  field_name = 6,
  field_right = 7,
  field_then = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_else] = "else",
  [field_expression] = "expression",
  [field_initialiser] = "initialiser",
  [field_left] = "left",
  [field_name] = "name",
  [field_right] = "right",
  [field_then] = "then",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 3},
  [8] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_right, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_expression, 1},
  [3] =
    {field_left, 0},
    {field_right, 2},
  [5] =
    {field_initialiser, 3},
    {field_name, 1},
  [7] =
    {field_condition, 2},
    {field_then, 4},
  [9] =
    {field_condition, 0},
    {field_else, 4},
    {field_then, 2},
  [12] =
    {field_condition, 2},
    {field_else, 6},
    {field_then, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 2,
  [7] = 5,
  [8] = 3,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 19,
  [26] = 15,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 30,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 39,
  [42] = 42,
  [43] = 40,
  [44] = 37,
  [45] = 42,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 34,
  [54] = 35,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 56,
  [61] = 61,
  [62] = 58,
  [63] = 61,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 67,
  [70] = 70,
  [71] = 65,
  [72] = 64,
  [73] = 66,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 77,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 82,
  [85] = 83,
  [86] = 86,
  [87] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(33);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(13);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 't') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 7},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 38},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {(TSStateId)(-1)},
  [87] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(81),
    [sym__declaration] = STATE(58),
    [sym_variable_declaration] = STATE(61),
    [sym__statement] = STATE(58),
    [sym_expression_statement] = STATE(42),
    [sym_print_statement] = STATE(42),
    [sym_block_statement] = STATE(42),
    [sym_if_statement] = STATE(42),
    [sym__expression] = STATE(71),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [2] = {
    [sym__declaration] = STATE(62),
    [sym_variable_declaration] = STATE(63),
    [sym__statement] = STATE(62),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(2),
    [aux_sym_program_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(29),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [3] = {
    [sym__declaration] = STATE(62),
    [sym_variable_declaration] = STATE(63),
    [sym__statement] = STATE(62),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(3),
    [aux_sym_program_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(29),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [4] = {
    [sym__declaration] = STATE(58),
    [sym_variable_declaration] = STATE(61),
    [sym__statement] = STATE(58),
    [sym_expression_statement] = STATE(42),
    [sym_print_statement] = STATE(42),
    [sym_block_statement] = STATE(42),
    [sym_if_statement] = STATE(42),
    [sym__expression] = STATE(71),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(4),
    [aux_sym_program_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [5] = {
    [sym__declaration] = STATE(62),
    [sym_variable_declaration] = STATE(63),
    [sym__statement] = STATE(62),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(5),
    [aux_sym_program_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(43),
    [anon_sym_var] = ACTIONS(46),
    [anon_sym_print] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_if] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(60),
    [sym_number] = ACTIONS(63),
    [sym_string] = ACTIONS(63),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_nil] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(72),
    [anon_sym_DASH] = ACTIONS(72),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [6] = {
    [sym__declaration] = STATE(62),
    [sym_variable_declaration] = STATE(63),
    [sym__statement] = STATE(62),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(6),
    [aux_sym_program_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(29),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(75),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [7] = {
    [sym__declaration] = STATE(58),
    [sym_variable_declaration] = STATE(61),
    [sym__statement] = STATE(58),
    [sym_expression_statement] = STATE(42),
    [sym_print_statement] = STATE(42),
    [sym_block_statement] = STATE(42),
    [sym_if_statement] = STATE(42),
    [sym__expression] = STATE(71),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(7),
    [aux_sym_program_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(43),
    [anon_sym_var] = ACTIONS(77),
    [anon_sym_print] = ACTIONS(80),
    [anon_sym_LBRACE] = ACTIONS(83),
    [anon_sym_if] = ACTIONS(86),
    [anon_sym_LPAREN] = ACTIONS(60),
    [sym_number] = ACTIONS(63),
    [sym_string] = ACTIONS(63),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_nil] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(72),
    [anon_sym_DASH] = ACTIONS(72),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [8] = {
    [sym__declaration] = STATE(62),
    [sym_variable_declaration] = STATE(63),
    [sym__statement] = STATE(62),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(8),
    [aux_sym_program_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(29),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(89),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [9] = {
    [sym__statement] = STATE(34),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(9),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [10] = {
    [sym__statement] = STATE(35),
    [sym_expression_statement] = STATE(45),
    [sym_print_statement] = STATE(45),
    [sym_block_statement] = STATE(45),
    [sym_if_statement] = STATE(45),
    [sym__expression] = STATE(65),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(10),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_print] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_if] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [11] = {
    [sym__statement] = STATE(53),
    [sym_expression_statement] = STATE(42),
    [sym_print_statement] = STATE(42),
    [sym_block_statement] = STATE(42),
    [sym_if_statement] = STATE(42),
    [sym__expression] = STATE(71),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(11),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [12] = {
    [sym__statement] = STATE(54),
    [sym_expression_statement] = STATE(42),
    [sym_print_statement] = STATE(42),
    [sym_block_statement] = STATE(42),
    [sym_if_statement] = STATE(42),
    [sym__expression] = STATE(71),
    [sym__literal] = STATE(55),
    [sym_boolean] = STATE(32),
    [sym_group_expression] = STATE(55),
    [sym_unary_expression] = STATE(55),
    [sym_binary_expression] = STATE(55),
    [sym_ternary_expression] = STATE(55),
    [sym_assignment_expression] = STATE(55),
    [sym_comment] = STATE(12),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(13), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(70), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [45] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(14), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(38), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [90] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(15), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(66), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [135] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(16), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(64), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [180] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(17), 1,
      sym_comment,
    STATE(31), 1,
      sym__expression,
    STATE(32), 1,
      sym_boolean,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [225] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(18), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(72), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [270] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(19), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(67), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [315] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(20), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(48), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [360] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(21), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(49), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [405] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(22), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(50), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [450] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(23), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(51), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [495] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(24), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(52), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [540] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(25), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(69), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [585] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(26), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(73), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [630] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(27), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(68), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [675] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      sym_nil,
    STATE(28), 1,
      sym_comment,
    STATE(32), 1,
      sym_boolean,
    STATE(47), 1,
      sym__expression,
    ACTIONS(21), 2,
      sym_number,
      sym_string,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(27), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(55), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [720] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(91), 1,
      anon_sym_EQ,
    STATE(29), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(93), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [752] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(99), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(97), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [781] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    STATE(31), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(101), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [822] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(117), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [851] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(121), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [880] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(127), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(125), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [909] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(133), 1,
      anon_sym_else,
    STATE(35), 1,
      sym_comment,
    ACTIONS(129), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(131), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
  [940] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(99), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(97), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [969] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(137), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(135), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [998] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(139), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1027] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(143), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(145), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1056] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(149), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(147), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1085] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(143), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(145), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1114] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(151), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(153), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1143] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(149), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(147), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1172] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(135), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1201] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(151), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(153), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1230] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(157), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(155), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1259] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    STATE(47), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(159), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [1300] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(161), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1333] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    STATE(49), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(161), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [1374] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(161), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1411] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(161), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1446] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 1,
      sym_comment,
    ACTIONS(163), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(161), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1475] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(53), 1,
      sym_comment,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(125), 8,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_else,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1504] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(165), 1,
      anon_sym_else,
    STATE(54), 1,
      sym_comment,
    ACTIONS(129), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
  [1535] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(55), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(93), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1564] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(56), 1,
      sym_comment,
    ACTIONS(167), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(169), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1592] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(57), 1,
      sym_comment,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(173), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1620] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(58), 1,
      sym_comment,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(177), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1648] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(59), 1,
      sym_comment,
    ACTIONS(171), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(173), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1676] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(60), 1,
      sym_comment,
    ACTIONS(167), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(169), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1704] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(61), 1,
      sym_comment,
    ACTIONS(179), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(181), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1732] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(62), 1,
      sym_comment,
    ACTIONS(175), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(177), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1760] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(63), 1,
      sym_comment,
    ACTIONS(179), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number,
      sym_string,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(181), 7,
      anon_sym_var,
      anon_sym_print,
      anon_sym_if,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1788] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(183), 1,
      anon_sym_SEMI,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(64), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1829] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1870] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1911] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_SEMI,
    STATE(67), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1952] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_COLON,
    STATE(68), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1993] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_SEMI,
    STATE(69), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2034] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2075] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_SEMI,
    STATE(71), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2116] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(201), 1,
      anon_sym_SEMI,
    STATE(72), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2157] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 1,
      anon_sym_STAR,
    ACTIONS(113), 1,
      anon_sym_SLASH,
    ACTIONS(115), 1,
      anon_sym_QMARK,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      sym_comment,
    ACTIONS(103), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(105), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(107), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [2198] = 6,
    ACTIONS(205), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      aux_sym_comment_token2,
    ACTIONS(211), 1,
      anon_sym_STAR_SLASH,
    STATE(74), 1,
      sym_comment,
    STATE(75), 1,
      aux_sym_comment_repeat1,
  [2217] = 5,
    ACTIONS(205), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(213), 1,
      aux_sym_comment_token2,
    ACTIONS(216), 1,
      anon_sym_STAR_SLASH,
    STATE(75), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [2234] = 6,
    ACTIONS(205), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      aux_sym_comment_token2,
    ACTIONS(218), 1,
      anon_sym_STAR_SLASH,
    STATE(74), 1,
      aux_sym_comment_repeat1,
    STATE(76), 1,
      sym_comment,
  [2253] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(220), 1,
      anon_sym_EQ,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    STATE(77), 1,
      sym_comment,
  [2269] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(224), 1,
      anon_sym_EQ,
    ACTIONS(226), 1,
      anon_sym_SEMI,
    STATE(78), 1,
      sym_comment,
  [2285] = 4,
    ACTIONS(205), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_SLASH_STAR,
    STATE(79), 1,
      sym_comment,
    ACTIONS(228), 2,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
  [2299] = 4,
    ACTIONS(205), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(207), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(218), 1,
      aux_sym_comment_token1,
    STATE(80), 1,
      sym_comment,
  [2312] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    STATE(81), 1,
      sym_comment,
  [2325] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(82), 1,
      sym_comment,
  [2338] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_comment,
  [2351] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(236), 1,
      sym_identifier,
    STATE(84), 1,
      sym_comment,
  [2364] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_comment,
  [2377] = 1,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
  [2381] = 1,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 45,
  [SMALL_STATE(15)] = 90,
  [SMALL_STATE(16)] = 135,
  [SMALL_STATE(17)] = 180,
  [SMALL_STATE(18)] = 225,
  [SMALL_STATE(19)] = 270,
  [SMALL_STATE(20)] = 315,
  [SMALL_STATE(21)] = 360,
  [SMALL_STATE(22)] = 405,
  [SMALL_STATE(23)] = 450,
  [SMALL_STATE(24)] = 495,
  [SMALL_STATE(25)] = 540,
  [SMALL_STATE(26)] = 585,
  [SMALL_STATE(27)] = 630,
  [SMALL_STATE(28)] = 675,
  [SMALL_STATE(29)] = 720,
  [SMALL_STATE(30)] = 752,
  [SMALL_STATE(31)] = 781,
  [SMALL_STATE(32)] = 822,
  [SMALL_STATE(33)] = 851,
  [SMALL_STATE(34)] = 880,
  [SMALL_STATE(35)] = 909,
  [SMALL_STATE(36)] = 940,
  [SMALL_STATE(37)] = 969,
  [SMALL_STATE(38)] = 998,
  [SMALL_STATE(39)] = 1027,
  [SMALL_STATE(40)] = 1056,
  [SMALL_STATE(41)] = 1085,
  [SMALL_STATE(42)] = 1114,
  [SMALL_STATE(43)] = 1143,
  [SMALL_STATE(44)] = 1172,
  [SMALL_STATE(45)] = 1201,
  [SMALL_STATE(46)] = 1230,
  [SMALL_STATE(47)] = 1259,
  [SMALL_STATE(48)] = 1300,
  [SMALL_STATE(49)] = 1333,
  [SMALL_STATE(50)] = 1374,
  [SMALL_STATE(51)] = 1411,
  [SMALL_STATE(52)] = 1446,
  [SMALL_STATE(53)] = 1475,
  [SMALL_STATE(54)] = 1504,
  [SMALL_STATE(55)] = 1535,
  [SMALL_STATE(56)] = 1564,
  [SMALL_STATE(57)] = 1592,
  [SMALL_STATE(58)] = 1620,
  [SMALL_STATE(59)] = 1648,
  [SMALL_STATE(60)] = 1676,
  [SMALL_STATE(61)] = 1704,
  [SMALL_STATE(62)] = 1732,
  [SMALL_STATE(63)] = 1760,
  [SMALL_STATE(64)] = 1788,
  [SMALL_STATE(65)] = 1829,
  [SMALL_STATE(66)] = 1870,
  [SMALL_STATE(67)] = 1911,
  [SMALL_STATE(68)] = 1952,
  [SMALL_STATE(69)] = 1993,
  [SMALL_STATE(70)] = 2034,
  [SMALL_STATE(71)] = 2075,
  [SMALL_STATE(72)] = 2116,
  [SMALL_STATE(73)] = 2157,
  [SMALL_STATE(74)] = 2198,
  [SMALL_STATE(75)] = 2217,
  [SMALL_STATE(76)] = 2234,
  [SMALL_STATE(77)] = 2253,
  [SMALL_STATE(78)] = 2269,
  [SMALL_STATE(79)] = 2285,
  [SMALL_STATE(80)] = 2299,
  [SMALL_STATE(81)] = 2312,
  [SMALL_STATE(82)] = 2325,
  [SMALL_STATE(83)] = 2338,
  [SMALL_STATE(84)] = 2351,
  [SMALL_STATE(85)] = 2364,
  [SMALL_STATE(86)] = 2377,
  [SMALL_STATE(87)] = 2381,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(29),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(82),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(18),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(85),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(13),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(32),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(33),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(32),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(14),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(84),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(16),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(6),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(83),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ternary_expression, 5, .production_id = 7),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 7, .production_id = 8),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 7, .production_id = 8),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, .production_id = 6),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, .production_id = 6),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_expression, 3, .production_id = 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_expression, 3, .production_id = 3),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, .production_id = 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 4),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3, .production_id = 2),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3, .production_id = 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5, .production_id = 5),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5, .production_id = 5),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(79),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1),
  [230] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lox(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
