#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_EQ = 3,
  anon_sym_SEMI = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_print = 7,
  sym_number = 8,
  sym_string = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  sym_nil = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_BANG = 15,
  anon_sym_DASH = 16,
  anon_sym_COMMA = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_BANG_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_GT = 22,
  anon_sym_GT_EQ = 23,
  anon_sym_PLUS = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_QMARK = 27,
  anon_sym_COLON = 28,
  anon_sym_SLASH_SLASH = 29,
  aux_sym_comment_token1 = 30,
  anon_sym_SLASH_STAR = 31,
  aux_sym_comment_token2 = 32,
  anon_sym_STAR_SLASH = 33,
  sym_program = 34,
  sym__declaration = 35,
  sym_variable_declaration = 36,
  sym__statement = 37,
  sym_block_statement = 38,
  sym_expression_statement = 39,
  sym_print_statement = 40,
  sym__expression = 41,
  sym__literal = 42,
  sym_boolean = 43,
  sym_group_expression = 44,
  sym_unary_expression = 45,
  sym_binary_expression = 46,
  sym_ternary_expression = 47,
  sym_assignment_expression = 48,
  sym_comment = 49,
  aux_sym_program_repeat1 = 50,
  aux_sym_comment_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_print] = "print",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym__statement] = "_statement",
  [sym_block_statement] = "block_statement",
  [sym_expression_statement] = "expression_statement",
  [sym_print_statement] = "print_statement",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym_group_expression] = "group_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_ternary_expression] = "ternary_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_print] = anon_sym_print,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym__statement] = sym__statement,
  [sym_block_statement] = sym_block_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_print_statement] = sym_print_statement,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym_group_expression] = sym_group_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_ternary_expression] = sym_ternary_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_group_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_condition = 1,
  field_else = 2,
  field_expression = 3,
  field_left = 4,
  field_right = 5,
  field_then = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_else] = "else",
  [field_expression] = "expression",
  [field_left] = "left",
  [field_right] = "right",
  [field_then] = "then",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_right, 1},
  [1] =
    {field_expression, 1},
  [2] =
    {field_left, 0},
    {field_right, 2},
  [4] =
    {field_condition, 0},
    {field_else, 4},
    {field_then, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 4,
  [7] = 5,
  [8] = 2,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 12,
  [17] = 17,
  [18] = 18,
  [19] = 9,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 38,
  [43] = 43,
  [44] = 36,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 43,
  [49] = 49,
  [50] = 50,
  [51] = 41,
  [52] = 37,
  [53] = 49,
  [54] = 46,
  [55] = 55,
  [56] = 56,
  [57] = 47,
  [58] = 55,
  [59] = 40,
  [60] = 45,
  [61] = 56,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 70,
  [72] = 72,
  [73] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(33);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 7},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 38},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {(TSStateId)(-1)},
  [73] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(68),
    [sym__declaration] = STATE(52),
    [sym_variable_declaration] = STATE(61),
    [sym__statement] = STATE(52),
    [sym_block_statement] = STATE(47),
    [sym_expression_statement] = STATE(47),
    [sym_print_statement] = STATE(47),
    [sym__expression] = STATE(43),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [2] = {
    [sym__declaration] = STATE(52),
    [sym_variable_declaration] = STATE(61),
    [sym__statement] = STATE(52),
    [sym_block_statement] = STATE(47),
    [sym_expression_statement] = STATE(47),
    [sym_print_statement] = STATE(47),
    [sym__expression] = STATE(43),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_var] = ACTIONS(32),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_print] = ACTIONS(38),
    [sym_number] = ACTIONS(41),
    [sym_string] = ACTIONS(41),
    [anon_sym_true] = ACTIONS(44),
    [anon_sym_false] = ACTIONS(44),
    [sym_nil] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(50),
    [anon_sym_BANG] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [3] = {
    [sym__declaration] = STATE(52),
    [sym_variable_declaration] = STATE(61),
    [sym__statement] = STATE(52),
    [sym_block_statement] = STATE(47),
    [sym_expression_statement] = STATE(47),
    [sym_print_statement] = STATE(47),
    [sym__expression] = STATE(43),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(3),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_print] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [4] = {
    [sym__declaration] = STATE(37),
    [sym_variable_declaration] = STATE(56),
    [sym__statement] = STATE(37),
    [sym_block_statement] = STATE(57),
    [sym_expression_statement] = STATE(57),
    [sym_print_statement] = STATE(57),
    [sym__expression] = STATE(48),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(4),
    [aux_sym_program_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_print] = ACTIONS(64),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [5] = {
    [sym__declaration] = STATE(37),
    [sym_variable_declaration] = STATE(56),
    [sym__statement] = STATE(37),
    [sym_block_statement] = STATE(57),
    [sym_expression_statement] = STATE(57),
    [sym_print_statement] = STATE(57),
    [sym__expression] = STATE(48),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(5),
    [aux_sym_program_repeat1] = STATE(6),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(66),
    [anon_sym_print] = ACTIONS(64),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [6] = {
    [sym__declaration] = STATE(37),
    [sym_variable_declaration] = STATE(56),
    [sym__statement] = STATE(37),
    [sym_block_statement] = STATE(57),
    [sym_expression_statement] = STATE(57),
    [sym_print_statement] = STATE(57),
    [sym__expression] = STATE(48),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(6),
    [aux_sym_program_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(68),
    [anon_sym_print] = ACTIONS(64),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [7] = {
    [sym__declaration] = STATE(37),
    [sym_variable_declaration] = STATE(56),
    [sym__statement] = STATE(37),
    [sym_block_statement] = STATE(57),
    [sym_expression_statement] = STATE(57),
    [sym_print_statement] = STATE(57),
    [sym__expression] = STATE(48),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(7),
    [aux_sym_program_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(58),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_print] = ACTIONS(64),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [8] = {
    [sym__declaration] = STATE(37),
    [sym_variable_declaration] = STATE(56),
    [sym__statement] = STATE(37),
    [sym_block_statement] = STATE(57),
    [sym_expression_statement] = STATE(57),
    [sym_print_statement] = STATE(57),
    [sym__expression] = STATE(48),
    [sym__literal] = STATE(24),
    [sym_boolean] = STATE(26),
    [sym_group_expression] = STATE(24),
    [sym_unary_expression] = STATE(24),
    [sym_binary_expression] = STATE(24),
    [sym_ternary_expression] = STATE(24),
    [sym_assignment_expression] = STATE(24),
    [sym_comment] = STATE(8),
    [aux_sym_program_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_var] = ACTIONS(72),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_print] = ACTIONS(78),
    [sym_number] = ACTIONS(41),
    [sym_string] = ACTIONS(41),
    [anon_sym_true] = ACTIONS(44),
    [anon_sym_false] = ACTIONS(44),
    [sym_nil] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(50),
    [anon_sym_BANG] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(38), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [45] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(10), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(35), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [90] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(28), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [135] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(51), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [180] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(30), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [225] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(29), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [270] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym_comment,
    STATE(25), 1,
      sym__expression,
    STATE(26), 1,
      sym_boolean,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [315] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(41), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [360] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(17), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(39), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [405] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(50), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [450] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(42), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [495] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(32), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [540] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(33), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [585] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_comment,
    STATE(26), 1,
      sym_boolean,
    STATE(31), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(24), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [630] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(81), 1,
      anon_sym_EQ,
    STATE(23), 1,
      sym_comment,
    ACTIONS(85), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(83), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [662] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(85), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(83), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [691] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    STATE(25), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(87), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [732] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(103), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [761] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(107), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [790] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    STATE(28), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(111), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [831] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(113), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [860] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(115), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_QMARK,
      anon_sym_COLON,
  [895] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    STATE(31), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(113), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_QMARK,
      anon_sym_COLON,
  [932] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    STATE(32), 1,
      sym_comment,
    ACTIONS(115), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_COLON,
  [965] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    STATE(33), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(113), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [1006] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(117), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1035] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(121), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1064] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(125), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(127), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1091] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(129), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(131), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1118] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    STATE(38), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1159] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1200] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(141), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1227] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    STATE(41), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1268] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    STATE(42), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1309] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(147), 1,
      anon_sym_SEMI,
    STATE(43), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1350] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    ACTIONS(125), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1377] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(151), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(149), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1404] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(155), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1431] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 1,
      sym_comment,
    ACTIONS(159), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(157), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1458] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_SEMI,
    STATE(48), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1499] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 1,
      sym_comment,
    ACTIONS(163), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(165), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1526] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_COLON,
    STATE(50), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1567] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 1,
      anon_sym_STAR,
    ACTIONS(99), 1,
      anon_sym_SLASH,
    ACTIONS(101), 1,
      anon_sym_QMARK,
    ACTIONS(135), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_SEMI,
    STATE(51), 1,
      sym_comment,
    ACTIONS(89), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(91), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(93), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(95), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1608] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 1,
      sym_comment,
    ACTIONS(129), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1635] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(53), 1,
      sym_comment,
    ACTIONS(163), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(165), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1662] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(54), 1,
      sym_comment,
    ACTIONS(155), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(153), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1689] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(55), 1,
      sym_comment,
    ACTIONS(173), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1716] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(56), 1,
      sym_comment,
    ACTIONS(175), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(177), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1743] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(57), 1,
      sym_comment,
    ACTIONS(159), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(157), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1770] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(58), 1,
      sym_comment,
    ACTIONS(173), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(171), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1797] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(59), 1,
      sym_comment,
    ACTIONS(141), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(139), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1824] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(60), 1,
      sym_comment,
    ACTIONS(151), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(149), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1851] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(61), 1,
      sym_comment,
    ACTIONS(175), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1878] = 6,
    ACTIONS(179), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(183), 1,
      aux_sym_comment_token2,
    ACTIONS(185), 1,
      anon_sym_STAR_SLASH,
    STATE(62), 1,
      sym_comment,
    STATE(63), 1,
      aux_sym_comment_repeat1,
  [1897] = 5,
    ACTIONS(179), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(187), 1,
      aux_sym_comment_token2,
    ACTIONS(190), 1,
      anon_sym_STAR_SLASH,
    STATE(63), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [1914] = 6,
    ACTIONS(179), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(183), 1,
      aux_sym_comment_token2,
    ACTIONS(192), 1,
      anon_sym_STAR_SLASH,
    STATE(62), 1,
      aux_sym_comment_repeat1,
    STATE(64), 1,
      sym_comment,
  [1933] = 4,
    ACTIONS(179), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_SLASH_STAR,
    STATE(65), 1,
      sym_comment,
    ACTIONS(194), 2,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
  [1947] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(196), 1,
      anon_sym_EQ,
    ACTIONS(198), 1,
      anon_sym_SEMI,
    STATE(66), 1,
      sym_comment,
  [1963] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(200), 1,
      anon_sym_EQ,
    ACTIONS(202), 1,
      anon_sym_SEMI,
    STATE(67), 1,
      sym_comment,
  [1979] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
    STATE(68), 1,
      sym_comment,
  [1992] = 4,
    ACTIONS(179), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(181), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(192), 1,
      aux_sym_comment_token1,
    STATE(69), 1,
      sym_comment,
  [2005] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(206), 1,
      sym_identifier,
    STATE(70), 1,
      sym_comment,
  [2018] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(208), 1,
      sym_identifier,
    STATE(71), 1,
      sym_comment,
  [2031] = 1,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
  [2035] = 1,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 45,
  [SMALL_STATE(11)] = 90,
  [SMALL_STATE(12)] = 135,
  [SMALL_STATE(13)] = 180,
  [SMALL_STATE(14)] = 225,
  [SMALL_STATE(15)] = 270,
  [SMALL_STATE(16)] = 315,
  [SMALL_STATE(17)] = 360,
  [SMALL_STATE(18)] = 405,
  [SMALL_STATE(19)] = 450,
  [SMALL_STATE(20)] = 495,
  [SMALL_STATE(21)] = 540,
  [SMALL_STATE(22)] = 585,
  [SMALL_STATE(23)] = 630,
  [SMALL_STATE(24)] = 662,
  [SMALL_STATE(25)] = 691,
  [SMALL_STATE(26)] = 732,
  [SMALL_STATE(27)] = 761,
  [SMALL_STATE(28)] = 790,
  [SMALL_STATE(29)] = 831,
  [SMALL_STATE(30)] = 860,
  [SMALL_STATE(31)] = 895,
  [SMALL_STATE(32)] = 932,
  [SMALL_STATE(33)] = 965,
  [SMALL_STATE(34)] = 1006,
  [SMALL_STATE(35)] = 1035,
  [SMALL_STATE(36)] = 1064,
  [SMALL_STATE(37)] = 1091,
  [SMALL_STATE(38)] = 1118,
  [SMALL_STATE(39)] = 1159,
  [SMALL_STATE(40)] = 1200,
  [SMALL_STATE(41)] = 1227,
  [SMALL_STATE(42)] = 1268,
  [SMALL_STATE(43)] = 1309,
  [SMALL_STATE(44)] = 1350,
  [SMALL_STATE(45)] = 1377,
  [SMALL_STATE(46)] = 1404,
  [SMALL_STATE(47)] = 1431,
  [SMALL_STATE(48)] = 1458,
  [SMALL_STATE(49)] = 1499,
  [SMALL_STATE(50)] = 1526,
  [SMALL_STATE(51)] = 1567,
  [SMALL_STATE(52)] = 1608,
  [SMALL_STATE(53)] = 1635,
  [SMALL_STATE(54)] = 1662,
  [SMALL_STATE(55)] = 1689,
  [SMALL_STATE(56)] = 1716,
  [SMALL_STATE(57)] = 1743,
  [SMALL_STATE(58)] = 1770,
  [SMALL_STATE(59)] = 1797,
  [SMALL_STATE(60)] = 1824,
  [SMALL_STATE(61)] = 1851,
  [SMALL_STATE(62)] = 1878,
  [SMALL_STATE(63)] = 1897,
  [SMALL_STATE(64)] = 1914,
  [SMALL_STATE(65)] = 1933,
  [SMALL_STATE(66)] = 1947,
  [SMALL_STATE(67)] = 1963,
  [SMALL_STATE(68)] = 1979,
  [SMALL_STATE(69)] = 1992,
  [SMALL_STATE(70)] = 2005,
  [SMALL_STATE(71)] = 2018,
  [SMALL_STATE(72)] = 2031,
  [SMALL_STATE(73)] = 2035,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(71),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(9),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(26),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(27),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(26),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(17),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(10),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(70),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(7),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(19),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, .production_id = 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ternary_expression, 5, .production_id = 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_expression, 3, .production_id = 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_expression, 3, .production_id = 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_statement, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_statement, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(65),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [204] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lox(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
