#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 70
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 5

enum {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_EQ = 3,
  anon_sym_SEMI = 4,
  anon_sym_print = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  sym_number = 8,
  sym_string = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  sym_nil = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_BANG = 15,
  anon_sym_DASH = 16,
  anon_sym_COMMA = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_BANG_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_LT_EQ = 21,
  anon_sym_GT = 22,
  anon_sym_GT_EQ = 23,
  anon_sym_PLUS = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_QMARK = 27,
  anon_sym_COLON = 28,
  anon_sym_SLASH_SLASH = 29,
  aux_sym_comment_token1 = 30,
  anon_sym_SLASH_STAR = 31,
  aux_sym_comment_token2 = 32,
  anon_sym_STAR_SLASH = 33,
  sym_program = 34,
  sym__declaration = 35,
  sym_variable_declaration = 36,
  sym__statement = 37,
  sym_expression_statement = 38,
  sym_print_statement = 39,
  sym_block = 40,
  sym__expression = 41,
  sym__literal = 42,
  sym_boolean = 43,
  sym_group_expression = 44,
  sym_unary_expression = 45,
  sym_binary_expression = 46,
  sym_ternary_expression = 47,
  sym_assignment_expression = 48,
  sym_comment = 49,
  aux_sym_program_repeat1 = 50,
  aux_sym_block_repeat1 = 51,
  aux_sym_comment_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_print] = "print",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [sym_program] = "program",
  [sym__declaration] = "_declaration",
  [sym_variable_declaration] = "variable_declaration",
  [sym__statement] = "_statement",
  [sym_expression_statement] = "expression_statement",
  [sym_print_statement] = "print_statement",
  [sym_block] = "block",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym_group_expression] = "group_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_ternary_expression] = "ternary_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_comment] = "comment",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_print] = anon_sym_print,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym_program] = sym_program,
  [sym__declaration] = sym__declaration,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym__statement] = sym__statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym_print_statement] = sym_print_statement,
  [sym_block] = sym_block,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym_group_expression] = sym_group_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_ternary_expression] = sym_ternary_expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_comment] = sym_comment,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_print] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_print_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_group_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_ternary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_condition = 1,
  field_else = 2,
  field_expression = 3,
  field_left = 4,
  field_right = 5,
  field_then = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_else] = "else",
  [field_expression] = "expression",
  [field_left] = "left",
  [field_right] = "right",
  [field_then] = "then",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_right, 1},
  [1] =
    {field_expression, 1},
  [2] =
    {field_left, 0},
    {field_right, 2},
  [4] =
    {field_condition, 0},
    {field_else, 4},
    {field_then, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 8,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 16,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 38,
  [45] = 45,
  [46] = 46,
  [47] = 37,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 45,
  [53] = 39,
  [54] = 49,
  [55] = 41,
  [56] = 48,
  [57] = 40,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 69,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(20);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(31);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(33);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1)
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(5);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '<') ADVANCE(25);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '?') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '!') ADVANCE(19);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(41);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(40);
      if (lookahead == '/') ADVANCE(35);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 'p') ADVANCE(3);
      if (lookahead == 't') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_print);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 38},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {(TSStateId)(-1)},
  [69] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_print] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(64),
    [sym__declaration] = STATE(50),
    [sym_variable_declaration] = STATE(45),
    [sym__statement] = STATE(50),
    [sym_expression_statement] = STATE(39),
    [sym_print_statement] = STATE(39),
    [sym_block] = STATE(50),
    [sym__expression] = STATE(44),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(25),
    [sym_group_expression] = STATE(22),
    [sym_unary_expression] = STATE(22),
    [sym_binary_expression] = STATE(22),
    [sym_ternary_expression] = STATE(22),
    [sym_assignment_expression] = STATE(22),
    [sym_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [2] = {
    [sym__declaration] = STATE(50),
    [sym_variable_declaration] = STATE(45),
    [sym__statement] = STATE(50),
    [sym_expression_statement] = STATE(39),
    [sym_print_statement] = STATE(39),
    [sym_block] = STATE(50),
    [sym__expression] = STATE(44),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(25),
    [sym_group_expression] = STATE(22),
    [sym_unary_expression] = STATE(22),
    [sym_binary_expression] = STATE(22),
    [sym_ternary_expression] = STATE(22),
    [sym_assignment_expression] = STATE(22),
    [sym_comment] = STATE(2),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [anon_sym_print] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [3] = {
    [sym__declaration] = STATE(50),
    [sym_variable_declaration] = STATE(45),
    [sym__statement] = STATE(50),
    [sym_expression_statement] = STATE(39),
    [sym_print_statement] = STATE(39),
    [sym_block] = STATE(50),
    [sym__expression] = STATE(44),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(25),
    [sym_group_expression] = STATE(22),
    [sym_unary_expression] = STATE(22),
    [sym_binary_expression] = STATE(22),
    [sym_ternary_expression] = STATE(22),
    [sym_assignment_expression] = STATE(22),
    [sym_comment] = STATE(3),
    [aux_sym_program_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_var] = ACTIONS(34),
    [anon_sym_print] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(40),
    [sym_number] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [anon_sym_true] = ACTIONS(46),
    [anon_sym_false] = ACTIONS(46),
    [sym_nil] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(52),
    [anon_sym_BANG] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [4] = {
    [sym__declaration] = STATE(51),
    [sym_variable_declaration] = STATE(52),
    [sym__statement] = STATE(51),
    [sym_expression_statement] = STATE(53),
    [sym_print_statement] = STATE(53),
    [sym__expression] = STATE(38),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(25),
    [sym_group_expression] = STATE(22),
    [sym_unary_expression] = STATE(22),
    [sym_binary_expression] = STATE(22),
    [sym_ternary_expression] = STATE(22),
    [sym_assignment_expression] = STATE(22),
    [sym_comment] = STATE(4),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(58),
    [anon_sym_var] = ACTIONS(61),
    [anon_sym_print] = ACTIONS(64),
    [anon_sym_RBRACE] = ACTIONS(67),
    [sym_number] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(72),
    [anon_sym_false] = ACTIONS(72),
    [sym_nil] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(78),
    [anon_sym_BANG] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [5] = {
    [sym__declaration] = STATE(51),
    [sym_variable_declaration] = STATE(52),
    [sym__statement] = STATE(51),
    [sym_expression_statement] = STATE(53),
    [sym_print_statement] = STATE(53),
    [sym__expression] = STATE(38),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(25),
    [sym_group_expression] = STATE(22),
    [sym_unary_expression] = STATE(22),
    [sym_binary_expression] = STATE(22),
    [sym_ternary_expression] = STATE(22),
    [sym_assignment_expression] = STATE(22),
    [sym_comment] = STATE(5),
    [aux_sym_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(84),
    [anon_sym_print] = ACTIONS(86),
    [anon_sym_RBRACE] = ACTIONS(88),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [6] = {
    [sym__declaration] = STATE(51),
    [sym_variable_declaration] = STATE(52),
    [sym__statement] = STATE(51),
    [sym_expression_statement] = STATE(53),
    [sym_print_statement] = STATE(53),
    [sym__expression] = STATE(38),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(25),
    [sym_group_expression] = STATE(22),
    [sym_unary_expression] = STATE(22),
    [sym_binary_expression] = STATE(22),
    [sym_ternary_expression] = STATE(22),
    [sym_assignment_expression] = STATE(22),
    [sym_comment] = STATE(6),
    [aux_sym_block_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(84),
    [anon_sym_print] = ACTIONS(86),
    [anon_sym_RBRACE] = ACTIONS(90),
    [sym_number] = ACTIONS(17),
    [sym_string] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_nil] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(7), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(30), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [45] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(8), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(35), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [90] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(42), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [135] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(10), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(33), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [180] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(36), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [225] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(12), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(34), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [270] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(26), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [315] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(27), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [360] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(15), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(29), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [405] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(47), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [450] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(17), 1,
      sym_comment,
    STATE(24), 1,
      sym__expression,
    STATE(25), 1,
      sym_boolean,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [495] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(37), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [540] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(28), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [585] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_nil,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_comment,
    STATE(25), 1,
      sym_boolean,
    STATE(31), 1,
      sym__expression,
    ACTIONS(17), 2,
      sym_number,
      sym_string,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    STATE(22), 6,
      sym__literal,
      sym_group_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_ternary_expression,
      sym_assignment_expression,
  [630] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(92), 1,
      anon_sym_EQ,
    STATE(21), 1,
      sym_comment,
    ACTIONS(96), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(94), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [662] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(96), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(94), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [691] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(23), 1,
      sym_comment,
    ACTIONS(100), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(98), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [720] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    STATE(24), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(102), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [761] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(120), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(118), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [790] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(124), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(122), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [819] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    STATE(27), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(124), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(122), 9,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_QMARK,
      anon_sym_COLON,
  [854] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    STATE(28), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(122), 7,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_QMARK,
      anon_sym_COLON,
  [891] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    STATE(29), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(122), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [932] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    STATE(30), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(122), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_QMARK,
      anon_sym_COLON,
  [965] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    STATE(31), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(126), 4,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_COLON,
  [1006] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(130), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(128), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1035] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(134), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(132), 12,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_QMARK,
      anon_sym_COLON,
  [1064] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_COLON,
    STATE(34), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1105] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(140), 1,
      anon_sym_SEMI,
    STATE(35), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1146] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(142), 1,
      anon_sym_SEMI,
    STATE(36), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1187] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(144), 1,
      anon_sym_SEMI,
    STATE(37), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1228] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(146), 1,
      anon_sym_SEMI,
    STATE(38), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1269] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(150), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1296] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(154), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1323] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(158), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(156), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1350] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1391] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(164), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(162), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1418] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1459] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(170), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1486] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(174), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(172), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1513] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      anon_sym_STAR,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      anon_sym_QMARK,
    ACTIONS(136), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_SEMI,
    STATE(47), 1,
      sym_comment,
    ACTIONS(104), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(108), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(110), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1554] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(48), 1,
      sym_comment,
    ACTIONS(180), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(178), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1581] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 1,
      sym_comment,
    ACTIONS(184), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(182), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1608] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 1,
      sym_comment,
    ACTIONS(188), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(186), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1635] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(51), 1,
      sym_comment,
    ACTIONS(190), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
    ACTIONS(192), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
  [1661] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 1,
      sym_comment,
    ACTIONS(168), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(170), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1687] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(53), 1,
      sym_comment,
    ACTIONS(148), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(150), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1713] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(54), 1,
      sym_comment,
    ACTIONS(182), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(184), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1739] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(55), 1,
      sym_comment,
    ACTIONS(156), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(158), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1765] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(56), 1,
      sym_comment,
    ACTIONS(178), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(180), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1791] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(57), 1,
      sym_comment,
    ACTIONS(152), 6,
      anon_sym_RBRACE,
      sym_number,
      sym_string,
      anon_sym_LPAREN,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(154), 6,
      anon_sym_var,
      anon_sym_print,
      anon_sym_true,
      anon_sym_false,
      sym_nil,
      sym_identifier,
  [1817] = 6,
    ACTIONS(194), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(198), 1,
      aux_sym_comment_token2,
    ACTIONS(200), 1,
      anon_sym_STAR_SLASH,
    STATE(58), 1,
      sym_comment,
    STATE(59), 1,
      aux_sym_comment_repeat1,
  [1836] = 5,
    ACTIONS(194), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(202), 1,
      aux_sym_comment_token2,
    ACTIONS(205), 1,
      anon_sym_STAR_SLASH,
    STATE(59), 2,
      sym_comment,
      aux_sym_comment_repeat1,
  [1853] = 6,
    ACTIONS(194), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(198), 1,
      aux_sym_comment_token2,
    ACTIONS(207), 1,
      anon_sym_STAR_SLASH,
    STATE(58), 1,
      aux_sym_comment_repeat1,
    STATE(60), 1,
      sym_comment,
  [1872] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      anon_sym_EQ,
    ACTIONS(211), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      sym_comment,
  [1888] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(213), 1,
      anon_sym_EQ,
    ACTIONS(215), 1,
      anon_sym_SEMI,
    STATE(62), 1,
      sym_comment,
  [1904] = 4,
    ACTIONS(194), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    STATE(63), 1,
      sym_comment,
    ACTIONS(217), 2,
      aux_sym_comment_token2,
      anon_sym_STAR_SLASH,
  [1918] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_comment,
  [1931] = 4,
    ACTIONS(194), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(196), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(207), 1,
      aux_sym_comment_token1,
    STATE(65), 1,
      sym_comment,
  [1944] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(221), 1,
      sym_identifier,
    STATE(66), 1,
      sym_comment,
  [1957] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(223), 1,
      sym_identifier,
    STATE(67), 1,
      sym_comment,
  [1970] = 1,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
  [1974] = 1,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 90,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 225,
  [SMALL_STATE(13)] = 270,
  [SMALL_STATE(14)] = 315,
  [SMALL_STATE(15)] = 360,
  [SMALL_STATE(16)] = 405,
  [SMALL_STATE(17)] = 450,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 540,
  [SMALL_STATE(20)] = 585,
  [SMALL_STATE(21)] = 630,
  [SMALL_STATE(22)] = 662,
  [SMALL_STATE(23)] = 691,
  [SMALL_STATE(24)] = 720,
  [SMALL_STATE(25)] = 761,
  [SMALL_STATE(26)] = 790,
  [SMALL_STATE(27)] = 819,
  [SMALL_STATE(28)] = 854,
  [SMALL_STATE(29)] = 891,
  [SMALL_STATE(30)] = 932,
  [SMALL_STATE(31)] = 965,
  [SMALL_STATE(32)] = 1006,
  [SMALL_STATE(33)] = 1035,
  [SMALL_STATE(34)] = 1064,
  [SMALL_STATE(35)] = 1105,
  [SMALL_STATE(36)] = 1146,
  [SMALL_STATE(37)] = 1187,
  [SMALL_STATE(38)] = 1228,
  [SMALL_STATE(39)] = 1269,
  [SMALL_STATE(40)] = 1296,
  [SMALL_STATE(41)] = 1323,
  [SMALL_STATE(42)] = 1350,
  [SMALL_STATE(43)] = 1391,
  [SMALL_STATE(44)] = 1418,
  [SMALL_STATE(45)] = 1459,
  [SMALL_STATE(46)] = 1486,
  [SMALL_STATE(47)] = 1513,
  [SMALL_STATE(48)] = 1554,
  [SMALL_STATE(49)] = 1581,
  [SMALL_STATE(50)] = 1608,
  [SMALL_STATE(51)] = 1635,
  [SMALL_STATE(52)] = 1661,
  [SMALL_STATE(53)] = 1687,
  [SMALL_STATE(54)] = 1713,
  [SMALL_STATE(55)] = 1739,
  [SMALL_STATE(56)] = 1765,
  [SMALL_STATE(57)] = 1791,
  [SMALL_STATE(58)] = 1817,
  [SMALL_STATE(59)] = 1836,
  [SMALL_STATE(60)] = 1853,
  [SMALL_STATE(61)] = 1872,
  [SMALL_STATE(62)] = 1888,
  [SMALL_STATE(63)] = 1904,
  [SMALL_STATE(64)] = 1918,
  [SMALL_STATE(65)] = 1931,
  [SMALL_STATE(66)] = 1944,
  [SMALL_STATE(67)] = 1957,
  [SMALL_STATE(68)] = 1970,
  [SMALL_STATE(69)] = 1974,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(21),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(67),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(16),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(25),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(32),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(25),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(9),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(10),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(21),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(66),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(18),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(25),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(32),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(25),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(9),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(10),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_expression, 3, .production_id = 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_group_expression, 3, .production_id = 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ternary_expression, 5, .production_id = 4),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, .production_id = 3),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 5),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 3),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 1),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__declaration, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_statement, 3),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_print_statement, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 1),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2), SHIFT_REPEAT(63),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1),
  [219] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lox(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
